import type { AssistResponse } from "@/lib/types";

const ACTION_STYLES: Record<AssistResponse["action_type"], { label: string; cls: string }> = {
  STANDARD_ASSISTANCE: { label: "Standard Assistance", cls: "bg-emerald-500/15 text-emerald-300 ring-emerald-500/30" },
  CRITICAL_DIVERSION_AND_ASSISTANCE: {
    label: "Critical Diversion",
    cls: "bg-red-500/15 text-red-300 ring-red-500/40",
  },
  MEDICAL_PRIORITY: { label: "Medical Priority", cls: "bg-amber-500/15 text-amber-300 ring-amber-500/40" },
  ACCESSIBILITY_ROUTING: {
    label: "Accessibility Routing",
    cls: "bg-violet-500/15 text-violet-300 ring-violet-500/30",
  },
};

export function GuidanceCard({
  data,
  language,
  loading,
  error,
}: {
  data: AssistResponse | null;
  language: string;
  loading: boolean;
  error: string | null;
}) {
  const rtl = language === "Arabic";

  return (
    <section
      aria-labelledby="guidance-heading"
      aria-live="polite"
      aria-busy={loading}
      className="rounded-2xl border border-slate-800 bg-gradient-to-br from-slate-950/80 to-slate-900/60 p-5 min-h-[280px]"
    >
      <div className="flex flex-wrap items-center justify-between gap-2 mb-4">
        <h2 id="guidance-heading" className="text-sm font-semibold uppercase tracking-widest text-cyan-300">
          🤖 AI Operational Guidance
        </h2>
        {data && (
          <div className="flex items-center gap-2">
            <span className={`rounded-full px-2.5 py-0.5 text-xs font-medium ring-1 ${ACTION_STYLES[data.action_type].cls}`}>
              {ACTION_STYLES[data.action_type].label}
            </span>
            <span
              className={`rounded-full px-2 py-0.5 text-[10px] font-mono uppercase tracking-wider ${data.source === "gemini" ? "bg-cyan-500/15 text-cyan-300 ring-1 ring-cyan-500/30" : "bg-slate-700/50 text-slate-300 ring-1 ring-slate-600"}`}
              title={data.source === "gemini" ? "Generated by Gemini 2.5 Flash" : "Deterministic fallback engine (LLM unreachable)"}
            >
              {data.source === "gemini" ? "Gemini" : "Fallback"}
            </span>
          </div>
        )}
      </div>

      {error && (
        <div role="alert" className="rounded-lg border border-red-500/40 bg-red-950/40 p-3 text-sm text-red-200">
          {error}
        </div>
      )}

      {loading && !data && (
        <div className="space-y-3">
          <div className="h-4 w-2/3 animate-pulse rounded bg-slate-800" />
          <div className="h-4 w-full animate-pulse rounded bg-slate-800" />
          <div className="h-4 w-4/5 animate-pulse rounded bg-slate-800" />
          <div className="h-20 w-full animate-pulse rounded bg-slate-800/60" />
        </div>
      )}

      {!loading && !data && !error && (
        <p className="text-sm text-slate-500">
          Submit a dispatch to see explainable AI routing, a reassuring script, and a translated response.
        </p>
      )}

      {data && (
        <div className="space-y-4">
          {data.recommended_gate_redirect && (
            <div className="flex items-center gap-3 rounded-lg border border-red-500/40 bg-red-950/30 p-3">
              <span aria-hidden className="text-2xl">↪</span>
              <div>
                <p className="text-xs uppercase tracking-wider text-red-300">Recommended diversion</p>
                <p className="text-lg font-semibold text-red-100">{data.recommended_gate_redirect}</p>
              </div>
            </div>
          )}

          <div>
            <p className="text-xs font-semibold uppercase tracking-wider text-slate-400">
              Explainable reasoning (ops log)
            </p>
            <p className="mt-1 text-sm text-slate-200">{data.explainable_reasoning}</p>
          </div>

          <div>
            <p className="text-xs font-semibold uppercase tracking-wider text-slate-400">
              Volunteer script — English
            </p>
            <p className="mt-1 rounded-lg bg-slate-900/70 p-3 text-slate-100 ring-1 ring-slate-800">
              {data.volunteer_script_english}
            </p>
          </div>

          <div>
            <p className="text-xs font-semibold uppercase tracking-wider text-slate-400">
              Translated for fan — {language}
            </p>
            <p
              lang={rtl ? "ar" : undefined}
              dir={rtl ? "rtl" : undefined}
              className="mt-1 rounded-lg bg-cyan-950/30 p-3 text-cyan-50 ring-1 ring-cyan-500/30"
            >
              {data.volunteer_script_translated}
            </p>
          </div>
        </div>
      )}
    </section>
  );
}
