/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TournamentRouteImport } from './routes/tournament'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogStadiumCrowdManagementBestPracticesRouteImport } from './routes/blog.stadium-crowd-management-best-practices'

const TournamentRoute = TournamentRouteImport.update({
  id: '/tournament',
  path: '/tournament',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogStadiumCrowdManagementBestPracticesRoute =
  BlogStadiumCrowdManagementBestPracticesRouteImport.update({
    id: '/blog/stadium-crowd-management-best-practices',
    path: '/blog/stadium-crowd-management-best-practices',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tournament': typeof TournamentRoute
  '/blog/stadium-crowd-management-best-practices': typeof BlogStadiumCrowdManagementBestPracticesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tournament': typeof TournamentRoute
  '/blog/stadium-crowd-management-best-practices': typeof BlogStadiumCrowdManagementBestPracticesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tournament': typeof TournamentRoute
  '/blog/stadium-crowd-management-best-practices': typeof BlogStadiumCrowdManagementBestPracticesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/tournament'
    | '/blog/stadium-crowd-management-best-practices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/tournament'
    | '/blog/stadium-crowd-management-best-practices'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/tournament'
    | '/blog/stadium-crowd-management-best-practices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TournamentRoute: typeof TournamentRoute
  BlogStadiumCrowdManagementBestPracticesRoute: typeof BlogStadiumCrowdManagementBestPracticesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tournament': {
      id: '/tournament'
      path: '/tournament'
      fullPath: '/tournament'
      preLoaderRoute: typeof TournamentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/stadium-crowd-management-best-practices': {
      id: '/blog/stadium-crowd-management-best-practices'
      path: '/blog/stadium-crowd-management-best-practices'
      fullPath: '/blog/stadium-crowd-management-best-practices'
      preLoaderRoute: typeof BlogStadiumCrowdManagementBestPracticesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TournamentRoute: TournamentRoute,
  BlogStadiumCrowdManagementBestPracticesRoute:
    BlogStadiumCrowdManagementBestPracticesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
